### ISSUE TITLE
Input as RGBD

### ISSUE THREAD

**Issue by VGrondin** [EPFL-VILAB/MultiMAE#24]
Hello, first of all thank you for your work it was a very interesting paper and releasing the code is very appreciated (it is well coded too).
I was wondering if you exprimented at some point with RGB-D input, where you would just concatenate the depth channel?

**Comment by roman-bachmann** [comment]
Hi @VGrondin,

Thanks! We never experimented with training on channel-wise concatenated RGB and depth, but it should be possible to train an MAE on that. We didn't do this, since concatenation removes the flexibility of using MultiMAE with only RGB inputs, only depth inputs, or with RGB and depth inputs. 
In addition, I expect we would not see the same cross-modal predictive coding abilities emerge, since any masked input would always have both RGB and depth information for the same spatial locations. In other words, a network trained this way would never encounter cases where one modality is completely missing from the input and has to be predicted from the other(s), or cases where some image locations have patches of some modalities but not others.

Best, Roman

**Comment by VGrondin** [comment]
Thank you for the explanation, I didn't think about the modality flexibility. Since Since depth would be always available for the application I am trying it on, I will run a quick experiment with 4 chanel RGBD inputs and let you know if performances improve.
Best
