### ISSUE TITLE
depth and semantic segmentation finetuning using frozen encoder

### ISSUE THREAD

**Issue by kalyani7195** [EPFL-VILAB/MultiMAE#29]
Hello! Thanks again for the great work!
I have a question about the following part of the fine-tuning code -- 

Why is there this raise NotImplementedError in the following file? https://github.com/EPFL-VILAB/MultiMAE/blob/main/run_finetuning_depth.py 

If we want the numbers by freezing the transformer should we just comment out the error and run?
Is there anything else that needs to be done? I just wanted to make sure. 

Thanks for your help,
Kalyani

```
    # Optionally freeze the encoder
    if args.freeze_transformer:
        raise NotImplementedError
        for param in model.encoder.parameters():
            param.requires_grad = False
```

**Comment by roman-bachmann** [comment]
Hi @kalyani7195,

We added this line because for NYU transfers we only performed full fine-tuning. 

It depends on what you want to do. If you only want to freeze the Transformer, you can just uncomment the `NotImplementedError`. Note that this does not freeze the input projections, nor the “class token”. If you want to freeze those too, make sure to handle `model.input_adapters` and `model.global_tokens`.

Best, Roman
