### ISSUE TITLE
Example usage of regular MAE Weights

### ISSUE THREAD

**Issue by mhamilton723** [EPFL-VILAB/MultiMAE#9]
Hey awesome work!  I am trying to figure out how to modify the demo notebook to use the regular MAE instead of multiMAE. In particular i comment out all depth and semseg info but the resulting image infilling looks corrupted. Could you by chance share an example of proper usage of the regular MAE weights? Thanks so much for the help!

**Comment by roman-bachmann** [comment]
Hi @mhamilton723,

Thanks! Our demo notebook does not support MAE weights, since there are some architectural differences between the decoders. Most importantly, we perform a cross-attention step from decoder queries to all encoded tokens. If you properly rename the MAE model weights (see one of our pre-trained weights for the keys and ignore all depth and semseg keys) and change the RGB output adapter to exactly match the MAE decoder, you might be able to get it working. I would, however, suggest just using the [official MAE notebook](https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb) instead if your usecase allows it.

Best, Roman

**Comment by roman-bachmann** [comment]
To follow up, in case you are using our MAE weights and not the ones from the official MAE notebook used for visualization: We trained the MAE with per-patch normalization, so any visualizations of model outputs might look corrupted.
